info:
  version: 0.9.0
  description: STGUTG configuration file

configuration:

# Network Functions
  amf_ngap: 192.168.43.3
  amf_port: 48412 #38412 #48412

  upf_port: 2152

  gnb_gtp: 192.168.43.1
  gnbg_port: 2152

  gnb_ngap: 192.168.43.1
  gnbn_port: 9487

# UE
  initial_imsi: "208930000000001"
  mcc: "208"
  mnc: "93"

# GNB data
  gnb_id: "\x00\x01\x02"
  gnb_bitlength: 24
  gnb_name: "free5gc"

# UE Authentication Data
  k: "8baf473f2f8fd09487cccbd7097c6862"
  opc: "8e27b6af0e692e750f32667a3b14605d"
  op: "8e27b6af0e692e750f32667a3b14605d"


  sst: 1
  sd: "010203"

  # Interaces for traffic
  src_iface: "enp0s8"
  dst_iface: "enp0s9"

  # Number of UEs to use in traffic mode
  ue_number: 1

  # Number of repetitions for each test (Test mode)
  ue_registration: 10
  ue_pdu: 10
  ue_service: 10
  ue_pdu_release: 10
  ue_deregistration: 10
